NumPy, short for "Numerical Python," is a powerful library in Python designed for scientific computing and data analysis. It provides a multidimensional array object, tools for integrating C/C++ and Fortran code, and a collection of routines for performing fast operations on arrays.
Here is how it enhances python capabilities.

1.Efficient multidimension array
At the core of NumPy is the ndarray object, an efficient multidimensional array that enables a wide variety of numerical operations.
Advandage
Unlike Python lists, NumPy arrays store data in contiguous memory locations. This arrangement allows faster access to data and more efficient storage, especially for large datasets.
2.NumPy enables element-wise operations on arrays, allowing developers to perform arithmetic and mathematical operations across entire arrays without writing loops.
3.
Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes, enabling operations between arrays without needing to reshape or replicate them manually.
4.
NumPy provides a suite of optimized mathematical functions for common operations like trigonometry, statistics, linear algebra, and more.
5.
NumPy offers tools for reshaping, transposing, stacking, splitting, and merging arrays.
6.NumPy is the foundation for many other data science libraries in Python, like pandas, SciPy, and scikit-learn, which use its arrays as their primary data structures.
7. NumPy allows precise control over data types in arrays, such as int8, int16, float32, and float64, which can reduce memory usage when dealing with large datasets.


2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?
In numpy both np.mean() and np.average() functions are used to calculate the average of an array, but they have some difference in there uses

where np.mean Computes the arithmetic mean (average) of the elements in an array or along a specified axis.
np.average(): it does not support weighting.It calculates the mean by simply summing all elements and dividing by the count.

Computes the weighted average of the elements in an array, if weights are provided. If weights are not provided, it functions the same as np.mean() by calculating the simple average.

Both np.mean() and np.average() return the same type, generally a scalar if no axis is specified or an array if computed along an axis. return answer in float.

Example trough code

In [ ]:
import numpy as np
data=np.array([10,20,30,40])
mean = np.mean(data) # it calculate simply mean
weights =np.array([1,2,3,4])
weighted_mean = np.average(data, weights=weights)
print("simple mean",mean) # 25.0
print("weighted mean",weighted_mean) #30.0

simple mean 25.0
weighted mean 30.0


3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.
1D array
In a 1-dimensional array, reversing the array simply means changing the order of elements.


In [ ]:
#using slicing
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reverse = arr_1d[::-1]
print(reverse)

[5 4 3 2 1]


In [ ]:
#using flip
reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)

[5 4 3 2 1]


In [ ]:
#Reversing a 2-D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
reverse_2d = arr_2d[::-1,]
print(reverse_2d)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
#Reversing 1 2-D array with np.flip with axis
reversed_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_rows_flip)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In NumPy, you can determine the data type of elements in an array using the dtype attribute. Data types are crucial in NumPy for memory management and performance, as they determine how much space each element occupies and how the data is processed.

In [ ]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


NumPy offers various data types, such as int8, int16, int32, and float64, each representing a different memory size. Choosing an appropriate data type minimizes memory usage, especially with large datasets.


In [ ]:
arr_small_ints = np.array([1, 2, 3], dtype=np.int8)  # Uses only 1 byte per integer
arr_large_ints = np.array([1, 2, 3], dtype=np.int64) # Uses 8 bytes per integer


Avoiding overflow
Selecting an appropriate data type prevents overflow issues, where values exceed the data type’s limit. For example, using int8 restricts values to the range -128 to 127, while int32 has a much larger range.

smaller data types reduce the amount of data the CPU processes at once, potentially speeding up operations. For example, using float32 instead of float64 can boost performance in applications that don’t require high precision.

it helps us memory management and performance(main point)

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, an ndarray (n-dimensional array) is a powerful, multi-dimensional array object that enables efficient computation and data handling in scientific computing. The ndarray is the core data structure in NumPy, supporting arrays of arbitrary dimensions and providing numerous features for data manipulation, mathematical operations, and indexing.

key features:

1.Homogeneous data
All elements in an ndarray are of the same data type (dtype), which is specified when the array is created. This consistency allows for efficient memory allocation and computation.

2.Multidimentional
ndarrays can have any number of dimensions, from 1D (similar to a list) to n-dimensional (like matrices and tensors). The shape of the array is determined by the number of dimensions and the size along each axis.

3.Efficient memory usage
ndarrays store data in contiguous memory blocks, making them more memory-efficient than Python lists, especially for large datasets. NumPy also allows us to choose specific data types (e.g., int32, float64) to save space.

4.vectorized operation:
NumPy arrays support element-wise operations and broadcasting, enabling you to perform mathematical operations on entire arrays without writing explicit loops. This vectorization leads to faster execution compared to traditional loops in Python.

5.Slicing and Indexing:
ndarrays provide powerful indexing options, including slicing, integer-based indexing, boolean indexing, and advanced indexing with arrays, allowing for flexible data selection and manipulation.


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays (ndarrays) offer substantial performance benefits over Python lists, especially for large-scale numerical operations. These advantages come primarily from efficient memory usage, support for vectorized operations, and optimized implementations in C. Here’s a deeper analysis of these benefits:

1. Memory Efficiency:

Fixed Data Types:

NumPy arrays store elements of a single data type (dtype), while Python lists can hold elements of mixed types. This homogeneity allows for contiguous memory allocation, where each element has a fixed size. In contrast, Python lists store pointers to objects, which takes more memory and leads to fragmented memory allocation.

Compact storage:

n a Python list of integers, each integer is stored as a Python object with metadata, which increases memory overhead. In a NumPy array, integers can be stored in a tightly packed format, which is more memory-efficient.

Example:

A NumPy array of 1,000,000 integers (e.g., np.int32) would require about 4 MB of memory (4 bytes per integer), while a Python list of the same integers would need significantly more memory because each integer is stored as a full-fledged Python object.

2. Vectorized Operations and Broadcasting:

No Looping in Python:

NumPy arrays support vectorized operations, where operations are applied to all elements at once without the need for Python loops. This is done internally by optimized C code, making it significantly faster than explicit loops in Python lists.

Broadcasting:

NumPy arrays can automatically align shapes of arrays to perform element-wise operations. For example, you can add a scalar or a smaller array to a larger array without looping, which is not possible with standard Python lists.

Example multiplying each element by 2


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = arr * 2  # Output: array([2, 4, 6, 8, 10])
print(result)

[ 2  4  6  8 10]


3. Speed of Mathematical Operations

Low-Level Implementation:
NumPy is implemented in C, and it leverages BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) libraries for optimized linear algebra routines. This results in faster execution for mathematical operations compared to Python’s high-level loops and list comprehensions.

Efficient Algorithms: Many of NumPy’s functions, such as np.sum() or np.dot(), are implemented in low-level languages, avoiding Python’s loop overhead and ensuring faster computation.

4. Parallelization and SIMD (Single Instruction, Multiple Data)

SIMD Optimization: NumPy operations take advantage of SIMD, where a single CPU instruction operates on multiple data points at once, which enhances speed for large arrays.
Multi-Threading: NumPy can also use multiple CPU cores for certain operations, allowing parallel execution, which is much faster than the single-threaded Python list operations.

5. Convenience with Built-in Functions

NumPy provides a vast array of optimized functions (e.g., np.mean, np.std, np.dot) for common operations. These are typically much faster than equivalent operations on Python lists because they avoid repeated function calls in Python and take advantage of compiled code.

6. Example: Comparing Performance on Large Data
Here’s a performance comparison for element-wise addition of two large arrays, one using a NumPy array and the other using a Python list:

In [ ]:
import numpy as np
import time

# Creating large datasets
size = 10**6
arr1 = np.arange(size)
arr2 = np.arange(size)
list1 = list(range(size))
list2 = list(range(size))

# Using NumPy array for addition
start_time = time.time()
result_np = arr1 + arr2
print("NumPy array addition took:", time.time() - start_time, "seconds")

# Using Python list for addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
print("Python list addition took:", time.time() - start_time, "seconds")


NumPy array addition took: 0.010515689849853516 seconds
Python list addition took: 0.1821577548980713 seconds


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively. These functions are particularly useful for combining arrays along different axes, and they simplify the process of array manipulation.

1. np.vstack()

Function: np.vstack() stacks arrays vertically (row-wise).

Usage: It combines arrays along the vertical axis (axis 0).

Input Requirement: Arrays must have the same number of columns, but they can differ in the number of rows.

In [ ]:
#example
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking them vertically
result = np.vstack((arr1, arr2))
print("Vertical Stack (vstack):\n", result)


Vertical Stack (vstack):
 [[1 2 3]
 [4 5 6]]


2. np.hstack()
Function: np.hstack() stacks arrays horizontally (column-wise).

Usage: It combines arrays along the horizontal axis (axis 1).

Input Requirement: Arrays must have the same number of rows, but they can differ in the number of columns.


In [ ]:
#EXAMPLE
# Creating two 2D arrays with the same number of rows
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])

# Stacking them horizontally
result = np.hstack((arr1, arr2))
print("Horizontal Stack (hstack):\n", result)


Horizontal Stack (hstack):
 [[1 2 3 4 5 6]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In NumPy, the fliplr() and flipud() functions are used to flip arrays along specific axes, providing different ways to reverse the order of elements in a 2D array (or higher-dimensional arrays). Here’s a breakdown of how each function works and their differences.

1. np.fliplr()

Function: np.fliplr() flips an array along the left-right (horizontal) axis.

Effect: Reverses the order of columns in each row of a 2D array.

Input Requirement: Works on arrays with two or more dimensions (2D or higher). If applied to a 1D array, it raises an error.

In [ ]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Applying fliplr
result = np.fliplr(arr)
print("Original Array:\n", arr)
print("\nFliplr Result:\n", result)

#In this example, np.fliplr() reverses the order of columns in each row, resulting in a horizontally flipped array.


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Fliplr Result:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


2. np.flipud()

Function: np.flipud() flips an array along the up-down (vertical) axis.

Effect: Reverses the order of rows in a 2D array.

Input Requirement: Works on arrays with one or more dimensions, so it can also be applied to a 1D array.

In [ ]:
# Using the same 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Applying flipud
result = np.flipud(arr)
print("Original Array:\n", arr)
print("\nFlipud Result:\n", result)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipud Result:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Here, np.flipud() reverses the order of rows, resulting in a vertically flipped array.

In [ ]:
#example with higher dimention
# Creating a 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

# Applying fliplr and flipud
fliplr_result = np.fliplr(arr_3d)
flipud_result = np.flipud(arr_3d)

print("Original 3D Array:\n", arr_3d)
print("\nFliplr Result (3D):\n", fliplr_result)
print("\nFlipud Result (3D):\n", flipud_result)


Original 3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

Fliplr Result (3D):
 [[[ 7  8  9]
  [ 4  5  6]
  [ 1  2  3]]

 [[16 17 18]
  [13 14 15]
  [10 11 12]]]

Flipud Result (3D):
 [[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The np.array_split() function in NumPy is used to split an array into a specified number of sub-arrays. It’s versatile and can handle cases where the array cannot be divided evenly, unlike np.split(), which requires equal splits and raises an error if the array cannot be split equally. Here’s a breakdown of array_split() and how it manages uneven splits:

np.array_split() Functionality

split an array into multiple sub array

Parameters:

array: The input array to split.
sections: The number of sections (sub-arrays) to divide the array into.
axis (optional): Specifies the axis along which to split the array (default is axis=0).


Handling Uneven Splits

When the number of elements in the array is not perfectly divisible by the specified sections, np.array_split() distributes the remaining elements across the first few sub-arrays, making them slightly larger than the others.

Even Split:

 If the number of elements is divisible by the sections, all sub-arrays will have the same size.
Uneven Split: If the number of elements is not divisible by the sections, array_split() ensures that the first few sub-arrays contain one more element than the others.

In [ ]:
#Example of uneven split

import numpy as np

# Creating an array with 10 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Splitting into 3 sub-arrays (10 elements / 3 sections is not an integer)
result = np.array_split(arr, 3)
print("Original Array:", arr)
print("\nArray Split Result (3 parts):")
for i, subarray in enumerate(result):
    print(f"Sub-array {i+1}: {subarray}")


Original Array: [ 1  2  3  4  5  6  7  8  9 10]

Array Split Result (3 parts):
Sub-array 1: [1 2 3 4]
Sub-array 2: [5 6 7]
Sub-array 3: [ 8  9 10]


In [ ]:
#specifying for higher dimension

arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

# Splitting along columns (axis=1)
result_axis1 = np.array_split(arr_2d, 3, axis=1)
print("\nArray Split Result along columns (axis=1):")
for i, subarray in enumerate(result_axis1):
    print(f"Sub-array {i+1}:\n{subarray}")



Array Split Result along columns (axis=1):
Sub-array 1:
[[1 2]
 [5 6]]
Sub-array 2:
[[3]
 [7]]
Sub-array 3:
[[4]
 [8]]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization and broadcasting are two core concepts in NumPy that significantly improve the efficiency of array operations by minimizing the need for explicit loops in Python. Here’s how they work and why they’re essential for performance:

1. Vectorization
Definition: Vectorization in NumPy refers to performing operations on entire arrays without using explicit Python loops. Instead, operations are applied element-wise at once across the whole array.
Purpose: It replaces the need for repetitive, loop-based calculations, which can be slow in Python due to its interpreted nature. NumPy leverages low-level, optimized C-based routines for these operations, leading to faster computation.



In [ ]:
#Example of vectorization
import numpy as np

# Creating a large array
arr = np.array([1, 2, 3, 4, 5])

# Vectorized operation (adds 2 to each element in the array)
result = arr + 2

print(result)


[3 4 5 6 7]


In this example, arr + 2 is a vectorized operation that adds 2 to each element without needing a loop. Internally, NumPy handles this using efficient, compiled code, making it much faster than if you had used a loop.

2.Broadcasting

Definition: Broadcasting in NumPy allows arrays with different shapes to be used in arithmetic operations, where one array’s shape is automatically “stretched” to match the other’s shape.

Purpose: Broadcasting enables operations between arrays of different sizes without creating unnecessary copies, saving both memory and computation time.

How Broadcasting Works

Broadcasting follows a set of rules to align array dimensions for operations. The two main rules are:

Match from Right to Left: Starting from the last dimension, NumPy compares each dimension of the two arrays. If they are equal or one of them is 1, the dimensions are compatible.
Shape Expansion: If an array’s dimension is 1, it’s expanded to match the corresponding dimension of the other array. If the dimensions are incompatible, NumPy raises an error


In [ ]:
# Creating a 2D array and a 1D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_1d = np.array([10, 20, 30])

# Broadcasting arr_1d to match arr_2d shape
result = arr_2d + arr_1d

print("2D Array:\n", arr_2d)
print("\n1D Array:", arr_1d)
print("\nResult of Broadcasting Addition:\n", result)


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array: [10 20 30]

Result of Broadcasting Addition:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


How Vectorization and Broadcasting Contribute to Efficiency

Reduced Python Overhead:

Vectorization removes the need for Python-level loops, avoiding interpreter overhead and allowing for faster, C-level execution.
Memory Efficiency: Broadcasting performs operations without explicitly copying data to match shapes, saving memory.


Parallel Processing:

NumPy operations are often internally optimized for parallel processing on CPUs, making large-scale calculations faster.
Together, these techniques make NumPy ideal for large-scale scientific and data-intensive applications where performance is crucial.


Now Starts practical question solutions


In [10]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
import numpy as np

array = np.random.randint(1,101,(3,3)) #upper limit is exclusive so we need to take 101 for 100
print("actual array")
print(array)
print("transposed array")
print(array.T)


actual array
[[53 26 45]
 [91 66 96]
 [90 19 76]]
transposed array
[[53 91 90]
 [26 66 19]
 [45 96 76]]


In [17]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
arr = np.random.randint(1,10,10)
print(arr)
print("reshaped into 2X5")
res1 = arr.reshape(2,5)
print(res1)
print("reshaped into 5X2")
res2 = arr.reshape(5,2)
print(res2)

[5 1 7 6 6 6 6 7 9 5]
reshaped into 2X5
[[5 1 7 6 6]
 [6 6 7 9 5]]
reshaped into 5X2
[[5 1]
 [7 6]
 [6 6]
 [6 7]
 [9 5]]


In [22]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
zero = np.zeros((6,6))
print(zero)
rand = np.random.rand(4,4)
zero[1:5,1:5] = rand
print(zero)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.66780321 0.93666405 0.71825428 0.92132859 0.        ]
 [0.         0.00425412 0.19927788 0.42970867 0.26265624 0.        ]
 [0.         0.75538219 0.34092028 0.46895833 0.40832972 0.        ]
 [0.         0.8149398  0.67137989 0.24705298 0.01616256 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [24]:
# Using NumPy, create an array of integers from 10 to 60 with a step of 5.
arr = np.arange(10,60,5)
print(arr)


[10 15 20 25 30 35 40 45 50 55]


In [31]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.
arr = ['python', 'numpy', 'pandas']

print("to upper case",np.char.upper(arr))
print("to lower case",np.char.lower(arr))
print("title case",np.char.title(arr))
print("capitalize",np.char.capitalize(arr))


to upper case ['PYTHON' 'NUMPY' 'PANDAS']
to lower case ['python' 'numpy' 'pandas']
title case ['Python' 'Numpy' 'Pandas']
capitalize ['Python' 'Numpy' 'Pandas']


In [32]:
# 6.Generate a NumPy array of words. Insert a space between each character of every word in the array.
arr = np.array(["python","hello","java","c++"])
spaced = np.char.join(" ",arr)
print(spaced)

['p y t h o n' 'h e l l o' 'j a v a' 'c + +']


In [39]:
#7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition_result = arr1 + arr2
print("Element-wise Addition:\n", addition_result)

# Perform element-wise subtraction
subtraction_result = arr1 - arr2
print("\nElement-wise Subtraction:\n", subtraction_result)

# Perform element-wise multiplication
multiplication_result = arr1 * arr2
print("\nElement-wise Multiplication:\n", multiplication_result)

# Perform element-wise division
division_result = arr1 / arr2
print("\nElement-wise Division:\n", division_result)


Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [41]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
identity = np.eye(5)
print(identity)
print("all diagonal element")
print(np.diagonal(identity))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
all diagonal element
[1. 1. 1. 1. 1.]


In [45]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.
arr = np.linspace(0,1000,100)

# Function to check for prime numbers
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in arr if is_prime(num)]

print("Prime Numbers in the Array:", prime_numbers)

Prime Numbers in the Array: [10.1010101010101, 20.2020202020202, 30.3030303030303, 40.4040404040404, 50.505050505050505, 60.6060606060606, 70.7070707070707, 80.8080808080808, 90.9090909090909, 101.01010101010101, 111.1111111111111, 121.2121212121212, 131.3131313131313, 141.4141414141414, 151.5151515151515, 161.6161616161616, 171.7171717171717, 181.8181818181818, 191.91919191919192, 202.02020202020202, 212.1212121212121, 222.2222222222222, 232.3232323232323, 242.4242424242424, 252.5252525252525, 262.6262626262626, 272.7272727272727, 282.8282828282828, 292.9292929292929, 303.030303030303, 313.1313131313131, 323.2323232323232, 333.3333333333333, 343.4343434343434, 353.5353535353535, 363.6363636363636, 373.73737373737373, 383.83838383838383, 393.93939393939394, 404.04040404040404, 414.1414141414141, 424.2424242424242, 434.3434343434343, 444.4444444444444, 454.5454545454545, 464.6464646464646, 474.7474747474747, 484.8484848484848, 494.9494949494949, 505.050505050505, 515.1515151515151, 525.

In [47]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#average
import numpy as np

temperatures = np.random.uniform(0, 40, size=30)
print("Daily Temperatures for a Month:", temperatures)

weeks = temperatures[:28].reshape(4, 7)
print("\nWeekly Temperatures:\n", weeks)


weekly_average = np.mean(weeks, axis=1)
print("\nWeekly Average Temperatures:", weekly_average)


Daily Temperatures for a Month: [32.26763916  2.3812235   8.2098729  16.21022415 30.19896352  3.77475307
 20.04756159 19.86697492 18.65380482 28.1282078  24.04710042 24.403803
  1.42206306  8.33368636 27.51534003 27.00196934 37.83964267 15.72047929
 26.56126242 12.95372593  0.29795213 22.91318774  4.29420149  4.41095144
  4.29047651 28.24917229 20.80467838  2.58929391 39.16782912  1.94575713]

Weekly Temperatures:
 [[32.26763916  2.3812235   8.2098729  16.21022415 30.19896352  3.77475307
  20.04756159]
 [19.86697492 18.65380482 28.1282078  24.04710042 24.403803    1.42206306
   8.33368636]
 [27.51534003 27.00196934 37.83964267 15.72047929 26.56126242 12.95372593
   0.29795213]
 [22.91318774  4.29420149  4.41095144  4.29047651 28.24917229 20.80467838
   2.58929391]]

Weekly Average Temperatures: [16.15574827 17.83652005 21.12719597 12.50742311]
